### PR TITLE
[DON'T MERGE] 1.0 support

### PR DESCRIPTION
**Pull request by filfat**
- [x] Update to protocol version _100_ (using 0.16 right now for testing)
- [ ] Handle Xbox connected players
- [ ] Things I've forgotten

### CODE REVIEW

**Comment by filfat** [comment]
#18

**Comment by mhsjlw** [comment]
We need to handle both XBOX and non-XBOX, also it'd be nice if you could make encryption optional... default of disabled?

**Comment by filfat** [comment]
Everything that worked in 0.16 seems to work on 1.0 (with the updated protocol). This includes but is not limited to start_game & batch (though batch seems to be a bit iffy and should be looked into).

I have managed to get chunks to render with @mhsjlw prismarine-chunk fork however there seems to be vertical duplication of the same 16x16x16 area (subchunk) so that should also be looked into.

**Comment by rom1504** [comment]
I didn't look at the code yet, but there seems to be some conflicts with master. Could you rebase ? (https://git-scm.com/book/en/v2/Git-Branching-Rebasing)

**Comment by mhsjlw** [comment]
@filfat, ah, I haven't even gotten a chance to test the chunks yet, at least they kind of work! But they're not done yet. I'll fix them up when I get a chance

**Comment by filfat** [comment]
@rom1504 I should probably rename the branch to "1.0" too.

**Pull request closed without merging**
